# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30da22652ac97bc2ed25822c51f3f5fd6ee613ac9a9f9380d4d0441540b0b2ef939fc7f6b683d0f6b675fa77d0a6a53e3f5d9a419bd0480984710fef400ed7e4

test:
  secret_key_base: 8662420b6b1eba3b28beca9df47d95fe459f8d64a92f29ea073e2eb3baee7a87af6d9f3d270692e6fdedb0fdd210eb790778cc9c908b19b30d2f28bee2cfc049

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
